"""Report generation for FigureLint-Bio results."""

from __future__ import annotations

import json


def generate_markdown_report(report: dict) -> str:
    """Render a lint report as a Markdown string.

    Parameters
    ----------
    report : dict
        Output of :func:`figurelint_bio.lint.lint_figure_spec`.

    Returns
    -------
    str
        A Markdown-formatted report suitable for display in a notebook,
        terminal, or documentation page.
    """
    spec = report.get("spec", {})
    title = spec.get("title") or f"{spec.get('field', '?')}/{spec.get('figure_type', '?')}"

    lines: list[str] = [
        f"# FigureLint-Bio Report: {title}",
        "",
        f"**Score:** {report['score']}/100  ",
        f"**Summary:** {report['summary']}",
        "",
    ]

    if report["errors"]:
        lines.append("## Errors")
        lines.append("")
        for issue in report["errors"]:
            lines.append(f"- **[ERROR]** `{issue['rule']}`")
            lines.append(f"  {issue['message'].strip()}")
            lines.append("")

    if report["warnings"]:
        lines.append("## Warnings")
        lines.append("")
        for issue in report["warnings"]:
            lines.append(f"- **[WARNING]** `{issue['rule']}`")
            lines.append(f"  {issue['message'].strip()}")
            lines.append("")

    if report["suggestions"]:
        lines.append("## Suggestions")
        lines.append("")
        for issue in report["suggestions"]:
            lines.append(f"- **[SUGGESTION]** `{issue['rule']}`")
            lines.append(f"  {issue['message'].strip()}")
            lines.append("")

    if not report["errors"] and not report["warnings"] and not report["suggestions"]:
        lines.append("No issues detected.  The spec satisfies all active lint rules.")
        lines.append("")

    lines.append("---")
    lines.append("*Generated by FigureLint-Bio — a pre-submission figure QA toolkit.*")

    return "\n".join(lines)


def generate_json_report(report: dict) -> str:
    """Serialise a lint report to a JSON string.

    The ``spec`` field is included for traceability.
    """
    return json.dumps(report, indent=2, default=str)
